{
  "name": "test_broken",
  "status": "broken",
  "statusDetails": {
    "message": "Exception: oops",
    "trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\npytest_Allure.py:9: Exception"
  },
  "start": 1627290490909,
  "stop": 1627290490909,
  "uuid": "c36dd888-96d7-407d-9fd9-9812d27fad2e",
  "historyId": "36124afcea75fcacc06774865a38248a",
  "testCaseId": "9a1ab45a7b22fdfb51852c14039b42d8",
  "fullName": "pytest_Allure#test_broken",
  "labels": [
    {
      "name": "suite",
      "value": "pytest_Allure"
    },
    {
      "name": "host",
      "value": "LAPTOP-V2RHK3K3"
    },
    {
      "name": "thread",
      "value": "20060-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "pytest_Allure"
    }
  ]
}